# Generated by Django 4.0.1 on 2023-06-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('show_id', models.AutoField(primary_key=True, serialize=False)),
                ('show_name', models.CharField(default='', max_length=50)),
                ('epesodes', models.IntegerField(default=0)),
                ('poster', models.ImageField(default='', upload_to='')),
            ],
        ),
    ]
