# Generated by Django 4.0.1 on 2023-06-19 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataBase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shows',
            name='epesodes',
        ),
        migrations.AddField(
            model_name='shows',
            name='episodes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MostPopular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataBase.shows')),
            ],
        ),
    ]
