# Generated by Django 4.0.1 on 2023-06-19 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataBase', '0002_remove_shows_epesodes_shows_episodes_mostpopular'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shows',
            old_name='episodes',
            new_name='epesodes',
        ),
        migrations.DeleteModel(
            name='MostPopular',
        ),
    ]
