# Generated by Django 4.0.1 on 2023-06-19 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataBase', '0003_rename_episodes_shows_epesodes_delete_mostpopular'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostPoplular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataBase.shows')),
            ],
        ),
    ]
