# Generated by Django 4.0.1 on 2023-06-19 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataBase', '0005_starplus'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarBharat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataBase.shows')),
            ],
        ),
    ]
