# Generated by Django 4.0.1 on 2023-06-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataBase', '0007_episodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodes',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
