# Generated by Django 4.0.1 on 2023-06-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataBase', '0008_episodes_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('mail', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
    ]
