# Generated by Django 4.0.1 on 2023-06-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataBase', '0011_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='width_image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
